import unittest

from ..sequence_gen import sequence_gen

class TestMystery4(unittest.TestCase):
    """To test for sequence generated by a function such that a list less than the length of the input is returned """

    def test_minimal_input(self):
        """Test for 0 input"""
        self.assertEqual(sequence_gen(0), [])
    def test_2(self):
        """Test for 0 input"""
        self.assertEqual(sequence_gen(5), [0, 1, 2, 3, 4])
    def test_string(self):
        """Should raise an assertion error because input is string"""
        with self.assertRaises(AssertionError):
            sequence_gen("a")
    def test_negative(self):
        """Should raise an assertion error because input is negative integer"""
        with self.assertRaises(AssertionError):
            sequence_gen("-9")
